protected/modules/frontend/models/Comment.php
<?php

class Comment extends CActiveRecord
{
    /**
     * The followings are the available columns in table 'tbl_comment':
     * @var integer $id
     * @var string $content
     * @var integer $status
     * @var integer $createtime
     * @var string $author
     * @var string $email
     * @var string $url
     * @var integer $postid
     */
    const STATUS_PENDING = 1;
    const STATUS_APPROVED = 2;

    public $verifyCode;

    /**
     * Returns the static model of the specified AR class.
     * @param string $className
     * @return mixed
     */
    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    /**
     * @return string the associated database table name
     */
    public function tableName()
    {
        return '{{comment}}';
    }

    /**
     * @return array validation rules for model attributes.
     */
    public function rules()
    {
        // NOTE: you should only define rules for those attributes that
        // will receive user inputs.
        return array(
            array('content, author, email', 'required'),
            array('author, email, url', 'length', 'max' => 128),
            array('verifyCode', 'captcha', 'allowEmpty' => !CCaptcha::checkRequirements()),
            array('email', 'email'),
            array('url', 'url'),
        );
    }

    /**
     * @return array relational rules.
     */
    public function relations()
    {
        // NOTE: you may need to adjust the relation name and the related
        // class name for the relations automatically generated below.
        return array(
            'post' => array(self::BELONGS_TO, 'Post', 'postid'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels()
    {
        return array(
            'id' => Yii::t('frontendmodel', 'ID'),
            'content' => Yii::t('frontendmodel', 'Content'),
            'status' => Yii::t('frontendmodel', 'Status'),
            'createtime' => Yii::t('frontendmodel', 'Create Time'),
            'author' => Yii::t('frontendmodel', 'Name'),
            'email' => Yii::t('frontendmodel', 'E-Mail'),
            'url' => Yii::t('frontendmodel', 'Website'),
            'postid' => Yii::t('frontendmodel', 'Post ID'),
        );
    }

    /**
     * Approves a comment.
     */
    public function approve()
    {
        $this->status = Comment::STATUS_APPROVED;
        $this->update(array('status'));
    }

    /**
     * @param Post the post that this comment belongs to. If null, the method
     * will query for the post.
     * @return string the permalink URL for this comment
     */
    public function getUrl($post = null)
    {
        if ($post === null) {
            $post = $this->post;
        }
        return $post->url . '#c' . $this->id;
    }

    /**
     * @return string the hyperlink display for the current comment's author
     */
    public function getAuthorLink()
    {
        return CHtml::encode($this->author);
    }

    /**
     * @return integer the number of comments that are pending approval
     */
    public function getPendingCommentCount()
    {
        return $this->count('status=' . self::STATUS_PENDING);
    }

    /**
     * @param integer the maximum number of comments that should be returned
     * @return array the most recently added comments
     */
    public function findRecentComments($limit = 10)
    {
        return $this->with('post')->findAll(array(
            'condition' => 't.status=' . self::STATUS_APPROVED,
            'order' => 't.createtime DESC',
            'limit' => $limit,
        ));
    }

    /**
     * This is invoked before the record is saved.
     * @return boolean whether the record should be saved.
     */
    protected function beforeSave()
    {
        if (parent::beforeSave()) {
            if ($this->isNewRecord) {
                $this->createtime = time();
            }
            return true;
        } else {
            return false;
        }
    }
}

protected/modules/frontend/models/Post.php
<?php

class Post extends CActiveRecord
{
    /**
     * The followings are the available columns in table 'tbl_post':
     * @var integer $id
     * @var string $title
     * @var string $content
     * @var string $tags
     * @var integer $status
     * @var integer $createtime
     * @var integer $updatetime
     * @var integer $authorid
     */
    const STATUS_DRAFT = 1;
    const STATUS_PUBLISHED = 2;
    const STATUS_ARCHIVED = 3;

    private $_oldTags;

    public $verifyCode;

    /**
     * Returns the static model of the specified AR class.
     * @param string $className
     * @return mixed
     */
    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    /**
     * @return string the associated database table name
     */
    public function tableName()
    {
        return '{{post}}';
    }

    /**
     * @return array validation rules for model attributes.
     */
    public function rules()
    {
        // NOTE: you should only define rules for those attributes that
        // will receive user inputs.
        return array(
            array('title, content, status, categoryid', 'required'),
            array('status', 'in', 'range' => array(1, 2, 3)),
            array('title', 'length', 'max' => 128),
            array('tags', 'match', 'pattern' => '/^[\w\s,]+$/',
                'message' => 'Tags can only contain word characters.'),
            array('tags', 'normalizeTags'),
            array('categoryid', 'safe'),
            array('title, status', 'safe', 'on' => 'search'),
        );
    }

    /**
     * @return array relational rules.
     */
    public function relations()
    {
        // NOTE: you may need to adjust the relation name and the related
        // class name for the relations automatically generated below.
        return array(
            'author' => array(self::BELONGS_TO, 'User', 'authorid'),
            'category' => array(self::BELONGS_TO, 'Category', 'categoryid'),
            'comments' => array(self::HAS_MANY, 'Comment', 'postid',
                'condition' => 'comments.status=' . Comment::STATUS_APPROVED,
                'order' => 'comments.createtime DESC'),
            'commentCount' => array(self::STAT, 'Comment', 'postid',
                'condition' => 'status=' . Comment::STATUS_APPROVED),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels()
    {
        return array(
            'id' => Yii::t('frontendmodel', 'ID'),
            'title' => Yii::t('frontendmodel', 'Title'),
            'content' => Yii::t('frontendmodel', 'Content'),
            'tags' => Yii::t('frontendmodel', 'Tags'),
            'status' => Yii::t('frontendmodel', 'Status'),
            'createtime' => Yii::t('frontendmodel', 'Create Time'),
            'updatetime' => Yii::t('frontendmodel', 'Update Time'),
            'authorid' => Yii::t('frontendmodel', 'Author'),
            'categoryid' => Yii::t('frontendmodel', 'Category ID'),
        );
    }

    /**
     * @return string the URL that shows the detail of the post
     */
    public function getUrl()
    {
        $module = strtolower(Yii::app()->getModule('frontend')->id);
        $controller = get_class($this);
        $controller[0] = strtolower($controller[0]);
        $params = array('id' => $this->id);

        return Yii::app()->urlManager->createUrl('/' . $module . '/' . $controller . '/view', $params);
    }

    /**
     * @return array a list of links that point to the post list filtered by every tag of this post
     */
    public function getTagLinks()
    {
        $links = array();
        $module = strtolower(Yii::app()->getModule('frontend')->id);
        $controller = get_class($this);
        $controller[0] = strtolower($controller[0]);

        foreach (Tag::string2array($this->tags) as $tag)
            $links[] = CHtml::link(CHtml::encode($tag), array('/' . $module . '/' . $controller . '/tag', 'tag' => $tag));
        return $links;
    }

    /**
     * Normalizes the user-entered tags.
     */
    public function normalizeTags()
    {
        $this->tags = Tag::array2string(array_unique(Tag::string2array($this->tags)));
    }

    /**
     * Adds a new comment to this post.
     * This method will set status and postid of the comment accordingly.
     * @param Comment the comment to be added
     * @return boolean whether the comment is saved successfully
     */
    public function addComment($comment)
    {
        if (Yii::app()->params['commentNeedApproval'] &&
            Yii::app()->user->checkAccess('guest')
        )
            $comment->status = Comment::STATUS_PENDING;
        else
            $comment->status = Comment::STATUS_APPROVED;
        $comment->postid = $this->id;
        return $comment->save();
    }

    /**
     * This is invoked when a record is populated with data from a find() call.
     */
    protected function afterFind()
    {
        parent::afterFind();
        $this->_oldTags = $this->tags;
    }

    /**
     * This is invoked before the record is saved.
     * @return boolean whether the record should be saved.
     */
    protected function beforeSave()
    {
        if (parent::beforeSave()) {
            if ($this->isNewRecord) {
                $this->createtime = $this->updatetime = time();
                $this->authorid = Yii::app()->user->id;
            } else {
                $this->updatetime = time();
            }
            return true;
        } else {
            return false;
        }
    }

    /**
     * This is invoked after the record is saved.
     */
    protected function afterSave()
    {
        parent::afterSave();
        Tag::model()->updateFrequency($this->_oldTags, $this->tags);
    }

    /**
     * This is invoked after the record is deleted.
     */
    protected function afterDelete()
    {
        parent::afterDelete();
        Comment::model()->deleteAll('postid=' . $this->id);
        Tag::model()->updateFrequency($this->tags, '');
    }

    /**
     * Retrieves the list of posts based on the current search/filter conditions.
     * @return CActiveDataProvider the data provider that can return the needed posts.
     */
    public function search()
    {
        $criteria = new CDbCriteria;

        $criteria->compare('title', $this->title, true);
        $criteria->compare('status', $this->status, true);

        return new CActiveDataProvider('Post', array(
            'criteria' => $criteria,
            'sort' => array(
                'defaultOrder' => 'status, updatetime DESC',
            ),
        ));
    }

    /**
     * @param integer the maximum number of comments that should be returned
     * @return array the most recently added comments
     */
    public function findRecentPosts($limit = 10)
    {
        $criteria = array(
            'condition' => 'status=' . self::STATUS_PUBLISHED,
            'order' => 'createtime DESC',
            'limit' => $limit,
        );
        return $this->findAll($criteria);
    }

    /**
     * @return null or the id
     */
    public function getNextId()
    {
        $record=self::model()->find(array(
            'condition' => 'id>:current_id',
            'order' => 'id ASC',
            'limit' => 1,
            'params'=>array(':current_id'=>$this->id),
        ));
        if($record!==null)
            return $record->id;
        return null;
    }

    /**
     * @return null or the id
     */
    public function getPreviousId()
    {
        $record=self::model()->find(array(
            'condition' => 'id<:current_id',
            'order' => 'id DESC',
            'limit' => 1,
            'params'=>array(':current_id'=>$this->id),
        ));
        if($record!==null)
            return $record->id;
        return null;
    }
}

protected/modules/backend/controllers/PostController.php
<?php

class PostController extends Controller
{
    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    public $layout = '/layouts/column2';

    /**
     * Declares class-based actions.
     */
    public function actions()
    {
        return array(
            // captcha action renders the CAPTCHA image displayed on the contact page
            'captcha' => array(
                'class' => 'CCaptchaAction',
                'backColor' => 0xF5F5F5,
            ),
        );
    }

    /**
     * @return array action filters
     */
    public function filters()
    {
        return array(
            'accessControl', // perform access control for CRUD operations
            'postOnly + delete', // we only allow deletion via POST request
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules()
    {
        return array(
            array(
                'allow', // allow specific users to access all actions
                'roles' => array('admin', 'editor'),
            ),
            array(
                'deny', // deny all users
                'roles' => array('guest', 'user'),
            ),
        );
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate()
    {
        $model = new BackendPost('create');
        if (isset($_POST['BackendPost'])) {
            $model->attributes = $_POST['BackendPost'];
            if ($model->save()) {
                $this->redirect(array('/frontend/post/view', 'id' => $model->id));
            }
        }
        $this->render('create', array(
            'model' => $model,
        ));
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     */
    public function actionUpdate($id)
    {
        $model = $this->loadModel($id);
        if (isset($_POST['BackendPost'])) {
            $model->attributes = $_POST['BackendPost'];
            if ($model->save()) {
                Yii::app()->user->setFlash('success', Yii::t('backendcontroller', 'Post was updated successfully.'));
            }
            $this->redirect(array('/frontend/post/view', 'id' => $id));
        }
        $this->render('update', array(
            'model' => $model,
        ));
    }

    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     */
    public function actionDelete($id)
    {
        if (Yii::app()->request->isPostRequest) {
            // we only allow deletion via POST request
            $this->loadModel($id)->delete();

            // if AJAX request (triggered by deletion via admin grid view),
            // we should not redirect the browser
            if (!isset($_GET['ajax'])) {
                $this->redirect(isset($_POST['returnUrl']) ?
                    $_POST['returnUrl'] :
                    array('index'));
            }
        }
    }

    /**
     * Manages all models.
     */
    public function actionIndex()
    {
        $model = new BackendPost('search');
        if (isset($_GET['BackendPost'])) {
            $model->attributes = $_GET['BackendPost'];
        }
        $this->render('index', array(
            'model' => $model,
        ));
    }

    /**
     * Suggests tags based on the current user input.
     * This is called via AJAX when the user is entering the tags input.
     */
    public function actionSuggestTags()
    {
        if (isset($_GET['term']) && ($keyword = trim($_GET['term'])) !== '') {
            $tags = BackendTag::model()->suggestTags($keyword);
            echo CJSON::encode($tags);
        }
    }

    /**
     * Returns the data model based on the primary key given in the GET variable.
     * If the data model is not found, an HTTP exception will be raised.
     * @param integer $id the ID of the model to be loaded
     * @return Post the loaded model
     * @throws CHttpException
     */
    public function loadModel($id)
    {
        $model = BackendPost::model()->findByPk($id);
        if ($model === null) {
            throw new CHttpException(404);
        }
        return $model;
    }
}

protected/modules/frontend/views/post/_comments.php
<?php foreach ($comments as $comment): ?>
    <div class="comment" id="c<?php echo $comment->id; ?>">
        <div class="author">
            <?php echo $comment->authorLink; ?> says:
        </div>
        <div class="content">
            <?php
            $this->beginWidget('CMarkdown', array('purifyOutput' => true));
            echo $comment->content;
            $this->endWidget();
            ?>
        </div>
        <div class="time">
            <?php echo 'on '. date('F j, Y \a\t h:i a', $comment->createtime); ?>
        </div>
    </div><!-- comment -->
<?php endforeach; ?>
<?php $this->widget('CLinkPager', array(
    'pages' => $pages,
    'nextPageLabel'=>'Older',
    'prevPageLabel'=>'Newer',
));

if (Yii::app()->user->hasFlash('success')) {
    $this->widget('booster.widgets.TbAlert', array(
        'fade' => true,
        'events' => array(),
        'htmlOptions' => array(),
        'alerts' => array( // configurations per alert type
            // success, info, warning, error or danger
            'success' => array('closeText' => 'YEEEEY')
        ),
    ));
} ?>

protected/modules/frontend/views/post/_form.php
<div class="form">

    <h3> Comments</h3>
    <?php if (Yii::app()->controller->action->id == 'view') : ?>
        <p class="note">Fields with <span class="required">*</span> are required.</p>
    <?php endif; ?>

    <?php $form = $this->beginWidget('booster.widgets.TbActiveForm', array(
        'id' => 'comment-form',
        'type' => 'horizontal',
        'enableAjaxValidation' => true,
        'htmlOptions' => array('class' => 'well'), // for inset effect
    )); ?>

    <?php echo $form->errorSummary($model); ?>

    <?php if (Yii::app()->user->checkAccess('guest')): ?>
        <?php echo $form->textFieldGroup(
            $model, 'author',
            array(
                'wrapperHtmlOptions' => array(
                    'class' => 'col-sm-5',
                ),
                'prepend' => '<i class="glyphicon glyphicon-user"></i>'
            )
        ); ?>

        <?php echo $form->textFieldGroup(
            $model, 'email',
            array(
                'wrapperHtmlOptions' => array(
                    'class' => 'col-sm-5',
                ),
                'prepend' => '@'
            )
        ); ?>
    <?php else: ?>
        <?php echo $form->textFieldGroup(
            $model, 'author',
            array(
                'wrapperHtmlOptions' => array(
                    'class' => 'col-sm-5',
                ),
                'widgetOptions' => array(
                    'htmlOptions' => array('value' => Yii::app()->user->name)
                ),
                'prepend' => '<i class="glyphicon glyphicon-user"></i>'
            )); ?>

        <?php echo $form->textFieldGroup(
            $model, 'email',
            array(
                'wrapperHtmlOptions' => array(
                    'class' => 'col-sm-5',
                ),
                'widgetOptions' => array(
                    'htmlOptions' => array('value' => Yii::app()->user->email,)
                ),
                'prepend' => '@'
            )); ?>
    <?php endif; ?>

    <?php echo $form->textFieldGroup(
        $model, 'url',
        array(
            'wrapperHtmlOptions' => array(
                'class' => 'col-sm-5',
            ),
            'prepend' => '<i class="glyphicon glyphicon-share"></i>'
        )); ?>

    <?php echo $form->textAreaGroup(
        $model,
        'content',
        array(
            'widgetOptions' => array(
                'htmlOptions' => array('rows' => 5),
            )
        )
    ); ?>

    <?php if (CCaptcha::checkRequirements()): ?>
        <?php echo $form->captchaGroup($model, 'verifyCode'); ?>
    <?php endif; ?>

    <div class="form-actions">
        <?php $this->widget('booster.widgets.TbButton', array(
            'label' => $model->isNewRecord ? 'Post' : 'Save',
            'context' => 'success',
            'buttonType' => 'submit'
        )); ?>
    </div>

    <?php $this->endWidget();
    unset($form); ?>

</div><!-- form -->

protected/modules/frontend/views/post/_view.php
<div class="post-wrapper">
    <div class="post" id="<?php echo $model->id; ?>">
        <div class="post-date">
            <span class="post-month"><?php echo date('M', $model->createtime); ?></span>
            <span class="post-day"><?php echo date('j', $model->createtime); ?></span>
        </div>
        <div class="post-title">
            <h3><?php echo CHtml::link(CHtml::encode($model->title), $model->url); ?></h3>
        </div>
        <div class="post-content">
            <?php $this->beginWidget('CMarkdown', array('purifyOutput' => true));
            if (strlen($model->content) > 300) {
                if (preg_match('/^.{1,300}\b/s', strip_tags($model->content), $content)) {
                    echo $content[0] . CHtml::link('<br />Read More &raquo;', $model->url);
                }
            } else {
                echo $model->content;
            }
            $this->endWidget(); ?>
        </div>
        <div class="post-editormenu">
            <i class="fa fa-tags"></i>
            <?php echo implode(', ', $model->tagLinks); ?> |
            <i class="fa fa-folder-open-o"></i>
            <?php echo CHtml::link(Category::model()->findByPK($model->categoryid)->name,
                Category::model()->findByPK($model->categoryid)->url); ?>
            <br/>
            <?php if (Yii::app()->user->checkAccess('admin')): ?>
                <i class="fa fa-pencil"></i>
                <?php echo CHtml::link('Update', array('/backend/post/update', 'id' => $model->id)); ?> |
            <?php endif; ?>
            <i class="fa fa-comments-o"></i>
            <?php echo CHtml::link("Comments ({$model->commentCount})", $model->url . '#comments'); ?> |
            <i class="fa fa-user"></i>
            <?php echo CHtml::link(CHtml::encode($model->author->username),
                array('/frontend/profile/view', 'id' => $model->authorid)); ?> |
            <i class="fa fa-calendar"></i> Last updated: <?php echo date('F j, Y \a\t h:i a', $model->updatetime); ?>
        </div>
    </div>
</div>

protected/modules/frontend/views/post/_viewbig.php
<div class="post-wrapper">
    <div class="post" id="<?php echo $model->id; ?>">
        <div class="post-date">
            <span class="post-month"><?php echo date('M', $model->createtime); ?></span>
            <span class="post-day"><?php echo date('j', $model->createtime); ?></span>
        </div>
        <div class="post-title">
            <h3><?php echo CHtml::link(CHtml::encode($model->title), $model->url); ?></h3>
        </div>
        <div class="post-content">
            <?php echo $model->content; ?>
        </div>
        <div class="post-menu">
            <?php if(!is_null($prev)) : ?>
                    <?php echo CHtml::link('<button type="button" class="btn btn-info pull-left"
                    data-toggle="tooltip" data-placement="top" title="Previous post">
                    <i class="fa fa-chevron-circle-left"></i></button>', $prev); ?>
            <?php endif; ?>
            <?php if(!is_null($next)) : ?>
                    <?php echo CHtml::link('<button type="button" class="btn btn-info pull-right"
                    data-toggle="tooltip" data-placement="top" title="Next post">
                    <i class="fa fa-chevron-circle-right"></i></button>', $next); ?>
            <?php endif; ?>
        </div>
        <div class="post-editormenu">
            <i class="fa fa-tags"></i>
            <?php echo implode(', ', $model->tagLinks); ?> |
            <i class="fa fa-folder-open-o"></i>
            <?php echo CHtml::link(Category::model()->findByPK($model->categoryid)->name,
                Category::model()->findByPK($model->categoryid)->url); ?>
            <br/>
            <?php if (Yii::app()->user->checkAccess('admin')): ?>
                <i class="fa fa-pencil"></i>
                <?php echo CHtml::link('Update', array('/backend/post/update', 'id' => $model->id)); ?> |
            <?php endif; ?>
            <i class="fa fa-comments-o"></i>
            <?php echo CHtml::link("Comments ({$model->commentCount})", $model->url . '#comments'); ?> |
            <i class="fa fa-user"></i>
            <?php echo CHtml::link(CHtml::encode($model->author->username),
                array('/frontend/profile/view', 'id' => $model->authorid)); ?> |
            <i class="fa fa-calendar"></i> Last updated: <?php echo date('F j, Y \a\t h:i a', $model->updatetime); ?>
        </div>

    </div>
</div>

protected/modules/frontend/views/post/list.php
<?php
/* @var $this PostController */
/* @var $model Post */
/* @var $form CActiveForm */

$this->breadcrumbs = array(
    Yii::app()->name
); ?>

<?php if (!empty($_GET['tag'])): ?>
    <legend>Posts tagged with <i><?php echo CHtml::encode($_GET['tag']); ?></i></legend>
<?php endif; ?>

<?php foreach ($models as $model): ?>
    <?php $this->renderPartial('_view', array(
        'model' => $model,
    )); ?>
<?php endforeach; ?>

<?php $this->widget('CLinkPager', array(
    'pages' => $pages,
    'nextPageLabel'=>'Older',
    'prevPageLabel'=>'Newer',
)) ?>

protected/modules/frontend/views/post/search.php
<?php
/* @var $this PostController */
/* @var $model Post */
/* @var $form CActiveForm */

$this->breadcrumbs = array(
    'Search Results'
); ?>

<div class="form">
    <?php if (!$search->hasErrors()): ?>
        <legend>
            <?php echo Yii::t('lan', 'Search Results'); ?> "<?php echo CHtml::encode($search->keyword); ?>"
        </legend>
    <?php else: ?>
        <legend>
            <?php echo CHtml::error($search, 'keyword'); ?>
        </legend>
    <?php endif; ?>

    <?php foreach ($models as $model): ?>
        <?php $this->renderPartial('_view', array('model' => $model)); ?>
    <?php endforeach; ?>

    <?php $this->widget('CLinkPager', array(
        'pages' => $pages,
        'nextPageLabel'=>'Older',
        'prevPageLabel'=>'Newer',
    )); ?>

</div>

protected/modules/frontend/views/post/tag.php
<?php
/* @var $this PostController */
/* @var $model Post */
/* @var $form CActiveForm */

$this->breadcrumbs = array(
    Yii::app()->name
); ?>

<?php if (!empty($_GET['tag'])): ?>
    <legend>Posts tagged with <i><?php echo CHtml::encode($_GET['tag']); ?></i></legend>
<?php endif; ?>

<?php foreach ($models as $model): ?>
    <?php $this->renderPartial('_view', array(
        'model' => $model,
    )); ?>
<?php endforeach; ?>

<?php $this->widget('CLinkPager', array(
    'pages' => $pages,
    'nextPageLabel'=>'Older',
    'prevPageLabel'=>'Newer',
)) ?>

protected/modules/frontend/views/post/view.php
<?php
/* @var $this PostController */
/* @var $model Post */
/* @var $form CActiveForm */

$this->breadcrumbs = array(
    $model->title
); ?>

<?php if (Yii::app()->user->hasFlash('success')) {
    $this->widget('booster.widgets.TbAlert', array(
        'fade' => true,
        'events' => array(),
        'htmlOptions' => array(),
        'alerts' => array( // configurations per alert type
            // success, info, warning, error or danger
            'success' => array('closeText' => false),
        ),
    ));
}

echo $this->renderPartial('_viewbig', array(
    'model' => $model,
    'next' => $next,
    'prev' => $prev,
)); ?>
<div id="comments">
    <legend>
        <?php echo Yii::t('lan', 'There is only a comment | There are {n} comments', $model->commentCount); ?>
    </legend>
</div>

<?php $this->renderPartial('_comments', array(
    'post' => $model,
    'comments' => $comments,
    'pages' => $pages,
));

if (Yii::app()->user->hasFlash('commentSubmitted')) {
    $this->widget('booster.widgets.TbAlert', array(
        'fade' => true,
        'events' => array(),
        'htmlOptions' => array(),
        'alerts' => array( // configurations per alert type
            // success, info, warning, error or danger
            'commentSubmitted' => array('closeText' => false),
        ),
    ));
} else {
    $this->renderPartial('_form', array(
        'model' => $comment,
    ));
} ?>